# Generated by Django 5.1.1 on 2024-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'ImageData',
            },
        ),
    ]
