export const questions = [
    {
        id: 1,
        question: 'What is the capital of France?',
        options: ['Berlin', 'Madrid', 'Paris', 'Rome'],
        answer: 2,
    },
    {
        id: 2,
        question: 'Who wrote "To Kill a Mockingbird"?',
        options: ['Harper Lee', 'J.K. Rowling', 'George Orwell', 'Jane Austen'],
        answer: 0,
    },
    {
        id: 3,
        question: 'What is the square root of 64?',
        options: ['6', '7', '8', '9'],
        answer: 2,
    },
    {
        id: 4,
        question: 'Which element has the chemical symbol "O"?',
        options: ['Oxygen', 'Gold', 'Osmium', 'Zinc'],
        answer: 0,
    },
    {
        id: 5,
        question: 'In which year did World War II end?',
        options: ['1940', '1945', '1939', '1950'],
        answer: 1,
    },
    {
        id: 6,
        question: 'Who painted the Mona Lisa?',
        options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'],
        answer: 2,
    },
    {
        id: 7,
        question: 'What is the largest ocean on Earth?',
        options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
        answer: 3,
    },
    {
        id: 8,
        question: 'Which planet is closest to the Sun?',
        options: ['Venus', 'Earth', 'Mercury', 'Mars'],
        answer: 2,
    },
    {
        id: 9,
        question: 'What is the longest river in the world?',
        options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
        answer: 1,
    },
    {
        id: 10,
        question: 'Who developed the theory of relativity?',
        options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Marie Curie'],
        answer: 1,
    },
    {
        id: 11,
        question: 'What is the hardest natural substance on Earth?',
        options: ['Gold', 'Iron', 'Diamond', 'Silver'],
        answer: 2,
    },
    {
        id: 12,
        question: 'Which language is the most spoken worldwide?',
        options: ['English', 'Mandarin Chinese', 'Spanish', 'Hindi'],
        answer: 1,
    },
    {
        id: 13,
        question: 'How many continents are there on Earth?',
        options: ['5', '6', '7', '8'],
        answer: 2,
    },
    {
        id: 14,
        question: 'What is the smallest prime number?',
        options: ['1', '2', '3', '5'],
        answer: 1,
    },
    {
        id: 15,
        question: 'Who was the first president of the United States?',
        options: ['Abraham Lincoln', 'John Adams', 'Thomas Jefferson', 'George Washington'],
        answer: 3,
    },
    {
        id: 16,
        question: 'Which country is famous for the kangaroo?',
        options: ['Brazil', 'Australia', 'India', 'South Africa'],
        answer: 1,
    },
    {
        id: 17,
        question: 'What is the chemical symbol for water?',
        options: ['H2O', 'CO2', 'O2', 'NaCl'],
        answer: 0,
    },
    {
        id: 18,
        question: 'What is the main ingredient in guacamole?',
        options: ['Tomato', 'Avocado', 'Cucumber', 'Potato'],
        answer: 1,
    },
    {
        id: 19,
        question: 'What is the tallest mountain in the world?',
        options: ['K2', 'Mount Everest', 'Kangchenjunga', 'Lhotse'],
        answer: 1,
    },
    {
        id: 20,
        question: 'Which planet is known as the Red Planet?',
        options: ['Earth', 'Mars', 'Venus', 'Jupiter'],
        answer: 1,
    },
    {
        id: 21,
        question: 'What is the largest mammal in the world?',
        options: ['Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus'],
        answer: 1,
    },
    {
        id: 22,
        question: 'What is the currency of Japan?',
        options: ['Yuan', 'Yen', 'Won', 'Dollar'],
        answer: 1,
    },
    {
        id: 23,
        question: 'Who wrote "Romeo and Juliet"?',
        options: ['William Shakespeare', 'Charles Dickens', 'Jane Austen', 'Mark Twain'],
        answer: 0,
    },
    {
        id: 24,
        question: 'What is the largest planet in our solar system?',
        options: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'],
        answer: 1,
    },
    {
        id: 25,
        question: 'What is the smallest country in the world?',
        options: ['Monaco', 'Maldives', 'Vatican City', 'San Marino'],
        answer: 2,
    },
    {
        id: 26,
        question: 'What is the capital of Canada?',
        options: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'],
        answer: 2,
    },
    {
        id: 27,
        question: 'What is the largest bird in the world?',
        options: ['Ostrich', 'Eagle', 'Albatross', 'Condor'],
        answer: 0,
    },
    {
        id: 28,
        question: 'Which country is known as the Land of the Rising Sun?',
        options: ['China', 'Japan', 'Korea', 'Vietnam'],
        answer: 1,
    },
    {
        id: 29,
        question: 'What is the chemical symbol for gold?',
        options: ['Au', 'Ag', 'Cu', 'Fe'],
        answer: 0,
    },
    {
        id: 30,
        question: 'What is the largest desert in the world?',
        options: ['Sahara', 'Arabian Desert', 'Gobi Desert', 'Kalahari Desert'],
        answer: 0,
    },
    {
        id: 31,
        question: 'Who painted the Sistine Chapel ceiling?',
        options: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'],
        answer: 1,
    },
    {
        id: 32,
        question: 'What is the currency of Russia?',
        options: ['Euro', 'Ruble', 'Dollar', 'Pound'],
        answer: 1,
    },
    {
        id: 33,
        question: 'What is the largest island in the world?',
        options: ['Greenland', 'Madagascar', 'Borneo', 'Sumatra'],
        answer: 0,
    },
    {
        id: 34,
        question: 'What is the capital of Australia?',
        options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
        answer: 2,
    },
    {
        id: 35,
        question: 'What is the chemical symbol for iron?',
        options: ['Fe', 'Au', 'Ag', 'Cu'],
        answer: 0,
    },
    {
        id: 36,
        question: 'What is the largest country in the world?',
        options: ['Canada', 'China', 'Russia', 'United States'],
        answer: 2,
    },
    {
        id: 37,
        question: 'What is the currency of China?',
        options: ['Yuan', 'Yen', 'Won', 'Dollar'],
        answer: 0,
    },
    {
        id: 38,
        question: 'What is the smallest ocean on Earth?',
        options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
        answer: 2,
    },
    {
        id: 39,
        question: 'Who wrote "Pride and Prejudice"?',
        options: ['Jane Austen', 'Charlotte Brontë', 'Emily Dickinson', 'Virginia Woolf'],
        answer: 0,
    },
    {
        id: 40,
        question: 'What is the chemical symbol for silver?',
        options: ['Ag', 'Au', 'Cu', 'Fe'],
        answer: 0,
    },
    {
        id: 41,
        question: 'What is the largest animal in the world?',
        options: ['Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus'],
        answer: 1,
    },
    {
        id: 42,
        question: 'What is the currency of the United Kingdom?',
        options: ['Euro', 'Ruble', 'Dollar', 'Pound'],
        answer: 3,
    },
    {
        id: 43,
        question: 'What is the capital of Brazil?',
        options: ['Rio de Janeiro', 'Brasília', 'São Paulo', 'Salvador'],
        answer: 1,
    },
    {
        id: 44,
        question: 'What is the chemical symbol for carbon?',
        options: ['C', 'Ca', 'Co', 'Cu'],
        answer: 0,
    },
    {
        id: 45,
        question: 'What is the largest lake in Africa?',
        options: ['Lake Victoria', 'Lake Tanganyika', 'Lake Malawi', 'Lake Chad'],
        answer: 0,
    },
    {
        id: 46,
        question: 'What is the currency of India?',
        options: ['Rupee', 'Ruble', 'Dollar', 'Pound'],
        answer: 0,
    },
    {
        id: 47,
        question: 'What is the smallest planet in our solar system?',
        options: ['Mercury', 'Venus', 'Earth', 'Mars'],
        answer: 0,
    },
];