# Generated by Django 5.1.1 on 2024-11-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileslink',
            name='file_name',
            field=models.CharField(default='filename', max_length=255),
        ),
    ]
